### ISSUE TITLE
Update to 3.17

### ISSUE THREAD

**Issue by keplerk** [shrewdlogarithm/PoE-Character-Log-Python#3]
Hello 3.17 is planned to be implemented ?

Regards

**Comment by shrewdlogarithm** [comment]
I've been out-of-the-loop with PoE (I found Scourge a total chore) but if the passive tree has been updated on the website, I can translate that and upload it so I'll take a look and if it's there/usable, I'll get that over and make the changes - hopefully before launch!

**Comment by keplerk** [comment]
> I've been out-of-the-loop with PoE (I found Scourge a total chore) but if the passive tree has been updated on the website, I can translate that and upload it so I'll take a look and if it's there/usable, I'll get that over and make the changes - hopefully before launch!

Totally agree, scourge was a total failure, and thanks if you could that would be helpful.

**Comment by shrewdlogarithm** [comment]
I've extracted the json from the POE site and created a new passive-tree JSON

I've also added a .txt file to explain how that works for future reference (in case I forget!)

I can't really test this until the league launches and there were errors in the tree last-league so we'll need to keep-an-eye for missing nodes in the output...
