### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by keplerk** [shrewdlogarithm/PoE-Character-Log-Python#4]
Hi I've ran the scan_all.py from scratch but i've encountered the following exception

```
  File "/home/pi/PoE-Character-Log-Python/charparser.py", line 10, in fixspec
    tolog("Special Character encountered " + specchar.group() + " - Charcode " + str(ord(specchar.group()[3:4])))
  File "/home/pi/PoE-Character-Log-Python/charparser.py", line 16, in tolog
    out = fixspec(out).rstrip()
  File "/home/pi/PoE-Character-Log-Python/charparser.py", line 8, in fixspec
    specchar = re.search(r"...[\x80-\xff]...",strin)
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.9/re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

Do you know why did this happen ?

Regards

**Comment by shrewdlogarithm** [comment]
I would take a guess there's a new skill/talent/ability - or a character name - using a foreign/special character which isn't encoded as we'd expect...

If you look at the top of charparser.py there's a function called fixspec which has 2 'special case' fixes for Maelstrom and Doppelganger already - we'll need to find what's causing the new problem and put something in to handle it ASAP

**Comment by keplerk** [comment]
Hi, i think i've found why it happened.

I've been watching over a spanish streamer, this is his poe profile

https://www.pathofexile.com/account/view-profile/KroximatuZ/characters

The one that triggered the exception was this character

![image](https://user-images.githubusercontent.com/4659797/152622618-e611b22c-168a-40b3-bbf9-2172a7f2b857.png)

La_Jauría_De_Kroxi

As you can see the "i" character is a special character.

Regards

**Comment by shrewdlogarithm** [comment]
There are actually 2 issues here and I've posted a fix for both

I've added a fix for that accented i - I really need to fix the encoding properly at some point but there are multiple encodings involved and it's a bit of a mess so...

I've also fixed my own error which caused the special character 'detector' to actually call itself over and over - which is what was throwing the actual error *DOH*

So it should work OK now and warn us of other issues in future WITHOUT crashing - thanks for reporting this!

**Comment by keplerk** [comment]
Thanks to you for fixing it, if i encounter any other thing, ill open a new ticket.
